# Generated by Django 6.0.2 on 2026-08-19 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApp', '0003_angajat_angajare_angajat_departament_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='angajat',
            old_name='departament_id',
            new_name='departament',
        ),
        migrations.RenameField(
            model_name='angajat',
            old_name='manager_id',
            new_name='manager',
        ),
        migrations.RenameField(
            model_name='departament',
            old_name='manager_id',
            new_name='manager',
        ),
    ]
