# Generated by Django 6.0.2 on 2026-08-19 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApp', '0004_rename_departament_id_angajat_departament_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departament',
            old_name='manager',
            new_name='manager_id',
        ),
    ]
