# Generated by Django 6.0.2 on 2026-08-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyApp', '0005_rename_manager_departament_manager_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departament',
            name='manager_id',
            field=models.IntegerField(null=True),
        ),
    ]
